org: fernandorojas
app: vpsolutions
service: vpsolutions-auth

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 30
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_SECRET_CHANGE_PASSWORD: ${env:JWT_SECRET_CHANGE_PASSWORD}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PATCH
      allowCredentials: false

plugins:
  - serverless-offline

functions:
  register:
    handler: handler.register
    events:
      - httpApi:
          path: /user/register
          method: post
  login:
    handler: handler.login
    events:
      - httpApi:
          path: /user/login
          method: post
  updateOldPassword:
    handler: handler.updateOldPassword
    events:
      - httpApi:
          path: /user/update_old_password
          method: patch
  updateOldLanguage:
    handler: handler.updateOldLanguage
    events:
      - httpApi:
          path: /user/update_old_language
          method: patch
  passwordSendEmail:
    handler: handler.passwordSendEmail
    events:
      - httpApi:
          path: /user/password_send_email
          method: post
  updatePasswordToken:
    handler: handler.updatePasswordToken
    events:
      - httpApi:
          path: /user/password_update_token
          method: post
