org: fernandorojas
app: vpsolutions
service: vpsolutions-auth

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - OPTIONS
        - GET
        - POST
      allowCredentials: false

plugins:
  - serverless-offline

functions:
  register:
    handler: handler.register
    events:
      - httpApi:
          path: /user/register
          method: post
  login:
    handler: handler.login
    events:
      - httpApi:
          path: /user/login
          method: post
